version: '3.8'

services:
  db:
    image: postgres:16
    container_name: pg-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notesdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: